name: Fetch AUDUSD 15m + Daily + Forecast

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/scripts/fetch_audusd.py"
      - ".github/workflows/fetch-audusd.yml"
      - "requirements.txt"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch data and forecasts
        run: python .github/scripts/fetch_audusd.py

      - name: Commit JSON if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            # Stash local JSON changes before pulling
            git stash push --include-untracked

            # Pull remote changes (rebasing) without failing the job
            git pull origin main --rebase || true

            # Re-apply our stashed changes
            git stash pop || true

            # Stage and commit any updated data artifacts
            git add data/*.json
            git commit -m "Update AUDUSD 15m + Daily + Forecast JSONs" || true

            # Push to main
            git push origin main
          else
            echo "No changes to commit"
          fi
