name: Fetch AUDUSD 15m + Daily

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/scripts/fetch_audusd.py"
      - ".github/workflows/fetch-audusd.yml"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Fetch AUDUSD 15m + Daily and write JSONs
        run: python .github/scripts/fetch_audusd.py

      - name: Commit JSON if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/audusd_15m.json data/usdaud_15m.json data/audusd_daily.json data/usdaud_daily.json
            git commit -m "Update AUDUSD 15m + Daily JSONs"
            git push
          else
            echo "No changes to commit"
          fi
